Mas 2.2.00
CAAPIM/iOS-MAS-UI pull request #81
Opened 2021-11-30 09:29 UTC by ysd24

2021-12-16 06:39 UTC, zakirjt approved these changes
looks fine

2021-12-16 06:43 UTC, zakirjt requested changes

2021-12-16 06:43 UTC, zakirjt commented on README.md
> + [get-started]: http://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/layer7-api-management/mobile-sdk-for-ca-mobile-api-gateway/2-2.html
Please check these links, they are not working.

2021-12-16 06:47 UTC, zakirjt commented on README.md
> + [get-started]: http://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/layer7-api-management/mobile-sdk-for-ca-mobile-api-gateway/2-2.html
As per @arindamhit , this links will be available after release, so please ignore the above.

2021-12-16 06:47 UTC, zakirjt approved these changes

2021-12-16 06:48 UTC, zakirjt commented on README.md
> + [get-started]: http://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/layer7-api-management/mobile-sdk-for-ca-mobile-api-gateway/2-2.html
As per @arindamhit , this links will be available after release, so please ignore the above.

2021-12-17 04:52 UTC, as666499 approved these changes
LGTM

2021-12-17 05:16 UTC, merged